Visit the Releases page for the doctl GitHub project, and find the appropriate archive for your operating system and architecture. You can download the archive from from your browser, or copy its URL and retrieve it to your home directory with wget or curl:

    cd ~
    wget https://github.com/digitalocean/doctl/releases/download/v1.6.0/doctl-1.6.0-linux-amd64.tar.gz

Or:

    cd ~
    curl -OL https://github.com/digitalocean/doctl/releases/download/v1.6.0/doctl-1.6.0-linux-amd64.tar.gz

Extract the binary. On GNU/Linux or OS X systems, you can use tar:

    tar xf ~/doctl-1.6.0-linux-amd64.tar.gz

On Windows systems, you should be able to double-click the zip archive to extract the doctl executable.

Move the doctl binary to somewhere in your path. For example, on GNU/Linux and OS X systems:

    sudo mv ~/doctl /usr/local/bin

=== Authenticating with DigitalOcean

Before proceeding, you'll need to retrieve a DigitalOcean access token to be stored in the doctl configuration file. This can be done by visiting the https://cloud.digitalocean.com/settings/api/tokens[Applications & API] section of the Control Panel. You can learn how to generate a token by following the https://www.digitalocean.com/community/tutorials/how-to-use-the-digitalocean-api-v2[DigitalOcean API guide].

Once you have generated a token, return to your terminal. To set up doctl and authorize it to use your account, type:

 $ doctl auth init

You will be prompted to enter the DigitalOcean access token that you generated in the DigitalOcean control panel:

 Output
 DigitalOcean access token: your_DO_token

After entering your token, you should receive confirmation that the credentials were accepted:

 Output
 Validating token: OK

This will create the necessary directory structure and configuration file to store your credentials. On OS X and Linux, the configuration file can be found at ${XDG_CONFIG_HOME}/doctl/config.yaml if the ${XDG_CONFIG_HOME} environmental variable is set, otherwise the config will be written to ~/.config/doctl/config.yaml. For Windows users, the config will be available at %APPDATA%/doctl/config/config.yaml.
